"""PR review command: fetch diff and generate AI code review."""

from __future__ import annotations

import json
import os
import subprocess
from typing import Optional

import openai
from rich.console import Console
from rich.markdown import Markdown

console = Console()

_SYSTEM_PROMPT = """You are an expert code reviewer with deep knowledge of software engineering best practices.

Review the provided pull request diff and provide thorough, actionable feedback.

Focus on:
- **Correctness**: logic errors, off-by-one errors, race conditions, edge cases
- **Security**: injection risks, insecure defaults, exposed secrets, improper input validation
- **Performance**: inefficient algorithms, N+1 queries, unnecessary allocations
- **Maintainability**: naming clarity, code structure, DRY violations, complexity
- **Test coverage**: missing tests for changed or new code paths

Format your response as structured Markdown. Reference file names and line numbers where possible.
Be constructive — suggest fixes, not just problems. Distinguish blocking issues from suggestions."""


def _get_pr_diff(pr: int, repo: Optional[str]) -> str:
    cmd = ["gh", "pr", "diff", str(pr)]
    if repo:
        cmd += ["--repo", repo]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return result.stdout


def _get_pr_metadata(pr: int, repo: Optional[str]) -> dict:
    cmd = ["gh", "pr", "view", str(pr), "--json", "title,body,headRefName,baseRefName,author"]
    if repo:
        cmd += ["--repo", repo]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return json.loads(result.stdout)


def _post_review_comment(pr: int, repo: Optional[str], body: str) -> None:
    cmd = ["gh", "pr", "review", str(pr), "--comment", "--body", body]
    if repo:
        cmd += ["--repo", repo]
    subprocess.run(cmd, check=True)


def run_review(pr: int, repo: Optional[str], model: str, post: bool) -> None:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        console.print("[red]Error:[/red] OPENAI_API_KEY is not set.")
        raise SystemExit(1)

    with console.status(f"Fetching PR #{pr}..."):
        try:
            diff = _get_pr_diff(pr, repo)
            meta = _get_pr_metadata(pr, repo)
        except subprocess.CalledProcessError as e:
            console.print(f"[red]GitHub CLI error:[/red] {e.stderr.strip()}")
            raise SystemExit(1)

    if len(diff) > 100_000:
        console.print("[yellow]Warning:[/yellow] Diff is large — truncating to 100K chars.")
        diff = diff[:100_000]

    user_content = (
        f"## PR #{pr}: {meta.get('title', '')}\n\n"
        f"**Author:** {meta.get('author', {}).get('login', 'unknown')}\n"
        f"**Branch:** `{meta.get('headRefName', '')}` → `{meta.get('baseRefName', '')}`\n\n"
        f"**Description:**\n{meta.get('body') or '(no description)'}\n\n"
        f"## Diff\n\n```diff\n{diff}\n```"
    )

    client = openai.OpenAI(api_key=api_key)

    with console.status(f"Reviewing with {model}..."):
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
            max_tokens=4096,
        )

    review_text = response.choices[0].message.content or ""

    console.print()
    console.print(Markdown(review_text))

    if post:
        footer = "\n\n---\n*Generated by [codex-maintainer](https://github.com/haruhi-abe/codex-maintainer)*"
        with console.status("Posting review to GitHub..."):
            _post_review_comment(pr, repo, f"## AI Code Review\n\n{review_text}{footer}")
        console.print("[green]Review posted to GitHub.[/green]")
